export DEVICE="P13001L"
export VENDOR="itel"
export DEVICE_TREE="device/itel/P13001L"
export CODENAME="VistaTab 30 Pro"
export WORKDIR="${WORKDIR:-/serverhive/ikanbandengultra/rom/src}"
export LOCAL_MANIFEST="https://github.com/ardiandideyashidiq/local_manifest-P13001L"
export LOCAL_MANIFEST_DIR=".repo/local_manifests"
export MIN_DISK_GB=350
export MIN_RAM_GB=48
export ENABLE_SIGNING=0
export ENABLE_GAPPS_AUTO=1
export GOFILE_TOKEN="ZCXFB6pBWMEWaCNEARTKCu8j7cloGNQ"
export ENABLE_UPLOAD=1
export TG_BOT_TOKEN="8534483917:AAEIjicXWPmojIrxFAvx3NMXAOEQxin_ev8"
export TG_CHAT_ID="6665891737"
export ENABLE_TG_NOTIFY=1
